name: Publish Template

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Add GitHub Package Source
      run: dotnet nuget add source --name github "https://nuget.pkg.github.com/izgaifullin/index.json" --username izgaifullin --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    
    - name: Pack
      run: dotnet pack --configuration Release
    
    - name: Push to GitHub Packages
      run: dotnet nuget push bin/Release/*.nupkg --source "https://nuget.pkg.github.com/izgaifullin/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}